import type { PropertyType } from "./listings";

export type SeedGroup = {
  id: string;
  name: string;
  areaFocus: string;
  description: string;
};

export type SeedListing = {
  id: string;
  groupId: string;
  title: string;
  area: string;
  neighborhood: string;
  propertyType: PropertyType;
  bedrooms: number;
  bathrooms: number;
  rentAnnual: number;
  agencyFee: number;
  legalFee: number;
  serviceCharge: number | null;
  cautionFee: number | null;
  description: string;
  amenities: string[];
  imageKey: string;
  hoursAgo: number;
  rawPost: string;
};

export const SEED_GROUPS: SeedGroup[] = [
  {
    id: "g-lekki",
    name: "Lekki & Ajah Available Homes",
    areaFocus: "Lekki · Ajah · Sangotedo",
    description: "Daily lets from agents covering the Lekki axis.",
  },
  {
    id: "g-vi",
    name: "VI · Ikoyi · Oniru Lets",
    areaFocus: "Victoria Island · Ikoyi · Oniru",
    description: "Island prestige and serviced apartments.",
  },
  {
    id: "g-ikeja",
    name: "Ikeja GRA & Mainland Flats",
    areaFocus: "Ikeja · Maryland · Magodo",
    description: "Mainland family flats and GRA houses.",
  },
  {
    id: "g-yaba",
    name: "Yaba · Surulere · Students",
    areaFocus: "Yaba · Surulere",
    description: "Self contains, mini flats, and walk-up buildings.",
  },
  {
    id: "g-gbagada",
    name: "Magodo · Maryland · Gbagada",
    areaFocus: "Magodo · Gbagada · Ketu",
    description: "Estate houses and quiet mainland streets.",
  },
  {
    id: "g-prestige",
    name: "Banana & Old Ikoyi Prestige",
    areaFocus: "Ikoyi · Banana Island",
    description: "High-end lettings, often off-market.",
  },
];

function fees(rent: number): { agencyFee: number; legalFee: number } {
  return { agencyFee: Math.round(rent * 0.1), legalFee: Math.round(rent * 0.1) };
}

export const SEED_LISTINGS: SeedListing[] = [
  {
    id: "lst-lekki-2bed-admiralty",
    groupId: "g-lekki",
    title: "2 bedroom flat in Lekki Phase 1",
    area: "Lekki",
    neighborhood: "Phase 1",
    propertyType: "flat",
    bedrooms: 2,
    bathrooms: 2,
    rentAnnual: 4_500_000,
    ...fees(4_500_000),
    serviceCharge: 600_000,
    cautionFee: null,
    description:
      "Newly built 2 bedroom apartment by Admiralty. Fitted kitchen, ensuite rooms, parking in a compact compound. Light is stable on prepaid.",
    amenities: ["Fitted kitchen", "POP ceiling", "24hrs light", "Treated water", "Parking", "Security", "Prepaid meter", "All rooms ensuite"],
    imageKey: "lekki-living",
    hoursAgo: 3,
    rawPost: "Newly built 2 bedroom apartment\nLekki Phase 1, by Admiralty\nRent: 4.5 million per annum\nService charge: 600k\nAgency 10% Legal 10%",
  },
  {
    id: "lst-lekki-3bed-ikate",
    groupId: "g-lekki",
    title: "3 bedroom flat in Ikate",
    area: "Lekki",
    neighborhood: "Ikate",
    propertyType: "flat",
    bedrooms: 3,
    bathrooms: 3,
    rentAnnual: 6_500_000,
    ...fees(6_500_000),
    serviceCharge: 800_000,
    cautionFee: null,
    description:
      "Spacious 3 bedroom in Ikate, two minutes off the express. All rooms ensuite, fitted kitchen, ample parking.",
    amenities: ["Fitted kitchen", "All rooms ensuite", "Parking", "Security", "Prepaid meter", "POP ceiling"],
    imageKey: "kitchen",
    hoursAgo: 7,
    rawPost: "3 bedroom flat Ikate Lekki\nRent 6.5m\nService charge 800k",
  },
  {
    id: "lst-lekki-1bed-osapa",
    groupId: "g-lekki",
    title: "1 bedroom apartment in Osapa",
    area: "Lekki",
    neighborhood: "Osapa",
    propertyType: "flat",
    bedrooms: 1,
    bathrooms: 1,
    rentAnnual: 2_800_000,
    ...fees(2_800_000),
    serviceCharge: 350_000,
    cautionFee: null,
    description: "Serviced 1 bedroom in Osapa London. Compact, bright, good for a single professional.",
    amenities: ["Serviced", "Fitted kitchen", "24hrs light", "Security", "Parking"],
    imageKey: "lekki-living",
    hoursAgo: 14,
    rawPost: "1 bedroom Osapa London\nRent 2.8m serviced",
  },
  {
    id: "lst-lekki-studio-chevron",
    groupId: "g-lekki",
    title: "Studio in Chevron",
    area: "Lekki",
    neighborhood: "Chevron",
    propertyType: "studio",
    bedrooms: 0,
    bathrooms: 1,
    rentAnnual: 1_800_000,
    ...fees(1_800_000),
    serviceCharge: 200_000,
    cautionFee: null,
    description: "New studio units inside Chevron estate. Tight but finished, with estate security and parking.",
    amenities: ["Security", "Parking", "Prepaid meter", "Newly built"],
    imageKey: "yaba-selfcontain",
    hoursAgo: 20,
    rawPost: "Studio Chevron Lekki\nRent 1.8m",
  },
  {
    id: "lst-ajah-4bed-adesanya",
    groupId: "g-lekki",
    title: "4 bedroom duplex in Abraham Adesanya",
    area: "Ajah",
    neighborhood: "Abraham Adesanya",
    propertyType: "duplex",
    bedrooms: 4,
    bathrooms: 4,
    rentAnnual: 6_000_000,
    ...fees(6_000_000),
    serviceCharge: 400_000,
    cautionFee: null,
    description: "Newly built 4 bedroom duplex with BQ on a tarred estate road. Inverter ready, CCTV, family compound.",
    amenities: ["Newly built", "BQ", "Inverter", "CCTV", "Fitted kitchen", "Parking", "Tarred road", "All rooms ensuite"],
    imageKey: "ajah-duplex",
    hoursAgo: 5,
    rawPost: "4 bedroom duplex with BQ\nAbraham Adesanya Ajah\nPrice 6m per annum",
  },
  {
    id: "lst-sangotedo-3bed",
    groupId: "g-lekki",
    title: "3 bedroom terrace in Sangotedo",
    area: "Sangotedo",
    neighborhood: "Abijo side",
    propertyType: "terrace",
    bedrooms: 3,
    bathrooms: 3,
    rentAnnual: 3_800_000,
    ...fees(3_800_000),
    serviceCharge: 250_000,
    cautionFee: null,
    description: "Terrace unit in a small gated cluster. Quiet, new finishes, easy access to the express.",
    amenities: ["Newly built", "Parking", "Security", "Fitted kitchen", "All rooms ensuite"],
    imageKey: "ajah-duplex",
    hoursAgo: 28,
    rawPost: "3 bedroom terrace Sangotedo\nRent 3.8m",
  },
  {
    id: "lst-vi-2bed-kofo",
    groupId: "g-vi",
    title: "2 bedroom apartment in Victoria Island",
    area: "Victoria Island",
    neighborhood: "Kofo Abayomi",
    propertyType: "flat",
    bedrooms: 2,
    bathrooms: 2,
    rentAnnual: 8_500_000,
    ...fees(8_500_000),
    serviceCharge: 1_200_000,
    cautionFee: null,
    description: "Serviced 2 bedroom with lagoon-facing living room. Lift, 24hr concierge, gym in the building.",
    amenities: ["Serviced", "Lift", "Gym", "24hrs light", "Security", "Parking", "Fitted kitchen"],
    imageKey: "vi-living",
    hoursAgo: 4,
    rawPost: "2 bedroom VI Kofo Abayomi\nRent 8.5m serviced",
  },
  {
    id: "lst-vi-3bed-oniru",
    groupId: "g-vi",
    title: "3 bedroom flat in Oniru",
    area: "Oniru",
    neighborhood: "Oniru Estate",
    propertyType: "flat",
    bedrooms: 3,
    bathrooms: 3,
    rentAnnual: 7_200_000,
    ...fees(7_200_000),
    serviceCharge: 900_000,
    cautionFee: null,
    description: "Bright 3 bedroom inside Oniru estate. Walkable to the beach road, two parking spaces.",
    amenities: ["Parking", "Security", "Fitted kitchen", "POP ceiling", "All rooms ensuite"],
    imageKey: "vi-living",
    hoursAgo: 11,
    rawPost: "3 bedroom Oniru estate\nRent 7.2m",
  },
  {
    id: "lst-ikoyi-2bed-parkview",
    groupId: "g-vi",
    title: "2 bedroom in Parkview",
    area: "Ikoyi",
    neighborhood: "Parkview",
    propertyType: "flat",
    bedrooms: 2,
    bathrooms: 2,
    rentAnnual: 9_000_000,
    ...fees(9_000_000),
    serviceCharge: 1_500_000,
    cautionFee: 1_000_000,
    description: "Quiet Parkview apartment, recently renovated. Estate security, generator, treated water.",
    amenities: ["Renovated", "Security", "Generator", "Treated water", "Parking", "Fitted kitchen"],
    imageKey: "ikoyi-bedroom",
    hoursAgo: 16,
    rawPost: "2 bedroom Parkview Ikoyi\nRent 9m",
  },
  {
    id: "lst-ikoyi-penthouse",
    groupId: "g-prestige",
    title: "4 bedroom penthouse in Old Ikoyi",
    area: "Ikoyi",
    neighborhood: "Old Ikoyi",
    propertyType: "penthouse",
    bedrooms: 4,
    bathrooms: 5,
    rentAnnual: 28_000_000,
    ...fees(28_000_000),
    serviceCharge: 4_000_000,
    cautionFee: 2_000_000,
    description: "Top-floor penthouse with terrace. Full backup power, staff quarters, basement parking.",
    amenities: ["Serviced", "Lift", "BQ", "Generator", "Parking", "Security", "Fitted kitchen", "Balcony"],
    imageKey: "ikoyi-bedroom",
    hoursAgo: 9,
    rawPost: "4 bedroom penthouse Old Ikoyi\nRent 28m",
  },
  {
    id: "lst-banana-3bed",
    groupId: "g-prestige",
    title: "3 bedroom apartment on Banana Island",
    area: "Ikoyi",
    neighborhood: "Banana Island",
    propertyType: "flat",
    bedrooms: 3,
    bathrooms: 3,
    rentAnnual: 22_000_000,
    ...fees(22_000_000),
    serviceCharge: 3_500_000,
    cautionFee: 2_000_000,
    description: "Island apartment in a low-rise block. Pool, gym, 24hr security. Available from next month.",
    amenities: ["Pool", "Gym", "Serviced", "Security", "Parking", "Lift", "All rooms ensuite"],
    imageKey: "vi-living",
    hoursAgo: 22,
    rawPost: "3 bedroom Banana Island\nRent 22m",
  },
  {
    id: "lst-ikeja-miniflat",
    groupId: "g-ikeja",
    title: "Mini flat in Ikeja GRA",
    area: "Ikeja",
    neighborhood: "GRA",
    propertyType: "mini-flat",
    bedrooms: 1,
    bathrooms: 1,
    rentAnnual: 1_600_000,
    ...fees(1_600_000),
    serviceCharge: null,
    cautionFee: 100_000,
    description: "Room and parlour mini flat on a quiet GRA street. Shared compound, borehole water, prepaid.",
    amenities: ["Prepaid meter", "Treated water", "Security", "Wardrobes"],
    imageKey: "ikeja-miniflat",
    hoursAgo: 6,
    rawPost: "Mini flat Ikeja GRA\nRent 1.6m",
  },
  {
    id: "lst-ikeja-2bed",
    groupId: "g-ikeja",
    title: "2 bedroom flat in Ikeja",
    area: "Ikeja",
    neighborhood: "Allen axis",
    propertyType: "flat",
    bedrooms: 2,
    bathrooms: 2,
    rentAnnual: 2_400_000,
    ...fees(2_400_000),
    serviceCharge: 150_000,
    cautionFee: null,
    description: "Upstairs 2 bedroom close to Allen. Tiled throughout, wardrobe in both rooms, street parking.",
    amenities: ["Wardrobes", "Prepaid meter", "POP ceiling", "Parking"],
    imageKey: "ikeja-miniflat",
    hoursAgo: 18,
    rawPost: "2 bedroom Ikeja Allen\nRent 2.4m",
  },
  {
    id: "lst-ikeja-3bed-gra",
    groupId: "g-ikeja",
    title: "3 bedroom house in Ikeja GRA",
    area: "Ikeja",
    neighborhood: "GRA",
    propertyType: "bungalow",
    bedrooms: 3,
    bathrooms: 3,
    rentAnnual: 5_500_000,
    ...fees(5_500_000),
    serviceCharge: null,
    cautionFee: 500_000,
    description: "Detached bungalow on a GRA close. Compound parking, generator house, recently painted.",
    amenities: ["Parking", "Generator", "Renovated", "Security", "BQ"],
    imageKey: "magodo-estate",
    hoursAgo: 30,
    rawPost: "3 bedroom bungalow Ikeja GRA\nRent 5.5m",
  },
  {
    id: "lst-maryland-2bed",
    groupId: "g-ikeja",
    title: "2 bedroom in Maryland",
    area: "Maryland",
    neighborhood: "Mende",
    propertyType: "flat",
    bedrooms: 2,
    bathrooms: 2,
    rentAnnual: 2_200_000,
    ...fees(2_200_000),
    serviceCharge: 120_000,
    cautionFee: null,
    description: "Clean 2 bedroom in Mende, Maryland. Close to the mall, prepaid, borehole.",
    amenities: ["Prepaid meter", "Treated water", "Parking", "Security"],
    imageKey: "ikeja-miniflat",
    hoursAgo: 40,
    rawPost: "2 bedroom Maryland Mende\nRent 2.2m",
  },
  {
    id: "lst-yaba-sc",
    groupId: "g-yaba",
    title: "Self contain in Yaba",
    area: "Yaba",
    neighborhood: "close to UNILAG",
    propertyType: "self-contain",
    bedrooms: 1,
    bathrooms: 1,
    rentAnnual: 850_000,
    ...fees(850_000),
    serviceCharge: null,
    cautionFee: 50_000,
    description: "Self contain a short walk from UNILAG. Wardrobe, tiled, prepaid. Best for a student or NYSC.",
    amenities: ["Wardrobes", "Prepaid meter", "Treated water"],
    imageKey: "yaba-selfcontain",
    hoursAgo: 2,
    rawPost: "Self contain Yaba close to UNILAG\nRent 850k yearly\nAgency 10% Legal 10%",
  },
  {
    id: "lst-yaba-miniflat",
    groupId: "g-yaba",
    title: "Mini flat in Yaba",
    area: "Yaba",
    neighborhood: "Sabo",
    propertyType: "mini-flat",
    bedrooms: 1,
    bathrooms: 1,
    rentAnnual: 1_200_000,
    ...fees(1_200_000),
    serviceCharge: null,
    cautionFee: 80_000,
    description: "Room and parlour in Sabo. Shared compound of four units, borehole, street is busy but the room is quiet at the back.",
    amenities: ["Treated water", "Prepaid meter", "Wardrobes"],
    imageKey: "ikeja-miniflat",
    hoursAgo: 8,
    rawPost: "Mini flat Sabo Yaba\nRent 1.2m",
  },
  {
    id: "lst-yaba-1bed",
    groupId: "g-yaba",
    title: "1 bedroom in Yaba",
    area: "Yaba",
    neighborhood: "Adekunle",
    propertyType: "flat",
    bedrooms: 1,
    bathrooms: 1,
    rentAnnual: 1_450_000,
    ...fees(1_450_000),
    serviceCharge: null,
    cautionFee: null,
    description: "Newly renovated 1 bedroom with kitchenette. Walking distance to the bus stop.",
    amenities: ["Renovated", "Prepaid meter", "Fitted kitchen"],
    imageKey: "yaba-selfcontain",
    hoursAgo: 26,
    rawPost: "1 bedroom Adekunle Yaba\nRent 1.45m",
  },
  {
    id: "lst-surulere-3bed",
    groupId: "g-yaba",
    title: "3 bedroom flat in Surulere",
    area: "Surulere",
    neighborhood: "Aguda",
    propertyType: "flat",
    bedrooms: 3,
    bathrooms: 2,
    rentAnnual: 2_800_000,
    ...fees(2_800_000),
    serviceCharge: 100_000,
    cautionFee: null,
    description: "Upstairs 3 bedroom in a four-flat building. Family street, school nearby, two parking spaces in front.",
    amenities: ["Parking", "Prepaid meter", "POP ceiling", "Wardrobes"],
    imageKey: "surulere-living",
    hoursAgo: 12,
    rawPost: "3 bedroom Surulere Aguda\nRent 2.8m",
  },
  {
    id: "lst-surulere-2bed",
    groupId: "g-yaba",
    title: "2 bedroom in Surulere",
    area: "Surulere",
    neighborhood: "Adeniran Ogunsanya",
    propertyType: "flat",
    bedrooms: 2,
    bathrooms: 2,
    rentAnnual: 2_100_000,
    ...fees(2_100_000),
    serviceCharge: 80_000,
    cautionFee: null,
    description: "2 bedroom a street off Adeniran Ogunsanya. Tiled, wardrobes, generator allowed.",
    amenities: ["Wardrobes", "Prepaid meter", "Parking"],
    imageKey: "surulere-living",
    hoursAgo: 33,
    rawPost: "2 bedroom Surulere\nRent 2.1m",
  },
  {
    id: "lst-magodo-4bed",
    groupId: "g-gbagada",
    title: "4 bedroom duplex in Magodo Phase 2",
    area: "Magodo",
    neighborhood: "Phase 2",
    propertyType: "duplex",
    bedrooms: 4,
    bathrooms: 4,
    rentAnnual: 7_500_000,
    ...fees(7_500_000),
    serviceCharge: 500_000,
    cautionFee: 500_000,
    description: "Family duplex inside Magodo Shangisha. Estate security, tarred roads, BQ, ample parking.",
    amenities: ["Security", "BQ", "Parking", "Tarred road", "Generator", "Fitted kitchen", "All rooms ensuite"],
    imageKey: "magodo-estate",
    hoursAgo: 10,
    rawPost: "4 bedroom duplex Magodo Phase 2\nRent 7.5m",
  },
  {
    id: "lst-magodo-3bed",
    groupId: "g-gbagada",
    title: "3 bedroom terrace in Magodo",
    area: "Magodo",
    neighborhood: "Phase 1",
    propertyType: "terrace",
    bedrooms: 3,
    bathrooms: 3,
    rentAnnual: 4_200_000,
    ...fees(4_200_000),
    serviceCharge: 300_000,
    cautionFee: null,
    description: "End-terrace in a quiet close. Newly painted, fitted kitchen, small front garden.",
    amenities: ["Renovated", "Fitted kitchen", "Parking", "Security", "All rooms ensuite"],
    imageKey: "magodo-estate",
    hoursAgo: 36,
    rawPost: "3 bedroom terrace Magodo Phase 1\nRent 4.2m",
  },
  {
    id: "lst-gbagada-2bed",
    groupId: "g-gbagada",
    title: "2 bedroom in Gbagada",
    area: "Gbagada",
    neighborhood: "Ifako",
    propertyType: "flat",
    bedrooms: 2,
    bathrooms: 2,
    rentAnnual: 1_900_000,
    ...fees(1_900_000),
    serviceCharge: 80_000,
    cautionFee: null,
    description: "2 bedroom in Ifako, Gbagada. New tiles, wardrobe, close to the express.",
    amenities: ["Wardrobes", "Prepaid meter", "Parking"],
    imageKey: "surulere-living",
    hoursAgo: 15,
    rawPost: "2 bedroom Gbagada Ifako\nRent 1.9m",
  },
  {
    id: "lst-ogudu-3bed",
    groupId: "g-gbagada",
    title: "3 bedroom in Ogudu GRA",
    area: "Ogudu",
    neighborhood: "GRA",
    propertyType: "flat",
    bedrooms: 3,
    bathrooms: 3,
    rentAnnual: 3_200_000,
    ...fees(3_200_000),
    serviceCharge: 200_000,
    cautionFee: null,
    description: "3 bedroom in Ogudu GRA. Gated street, two parking, all rooms ensuite.",
    amenities: ["All rooms ensuite", "Parking", "Security", "Fitted kitchen"],
    imageKey: "kitchen",
    hoursAgo: 44,
    rawPost: "3 bedroom Ogudu GRA\nRent 3.2m",
  },
  {
    id: "lst-ketu-sc",
    groupId: "g-gbagada",
    title: "Self contain in Ketu",
    area: "Ketu",
    neighborhood: "Alapere",
    propertyType: "self-contain",
    bedrooms: 1,
    bathrooms: 1,
    rentAnnual: 650_000,
    ...fees(650_000),
    serviceCharge: null,
    cautionFee: 40_000,
    description: "Affordable self contain in Alapere. Shared compound, borehole, prepaid.",
    amenities: ["Prepaid meter", "Treated water"],
    imageKey: "yaba-selfcontain",
    hoursAgo: 19,
    rawPost: "Self contain Ketu Alapere\nRent 650k",
  },
  {
    id: "lst-lekki-2bed-agungi",
    groupId: "g-lekki",
    title: "2 bedroom in Agungi",
    area: "Lekki",
    neighborhood: "Agungi",
    propertyType: "flat",
    bedrooms: 2,
    bathrooms: 2,
    rentAnnual: 3_600_000,
    ...fees(3_600_000),
    serviceCharge: 400_000,
    cautionFee: null,
    description: "2 bedroom off Agungi road. Not on the express, compound of six flats, parking for two cars.",
    amenities: ["Parking", "Security", "Fitted kitchen", "Prepaid meter", "All rooms ensuite"],
    imageKey: "ensuite",
    hoursAgo: 1,
    rawPost: "2 bedroom Agungi Lekki\nRent 3.6m",
  },
];
