/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as GroupsIdRouteImport } from './routes/groups.$id'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as ApiMediaIdRouteImport } from './routes/api/media.$id'
import { Route as ApiWhatsappHubRouteImport } from './routes/api/whatsapp/hub'
import { Route as ApiWhatsappIngestRouteImport } from './routes/api/whatsapp/ingest'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GroupsRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappHubRoute = ApiWhatsappHubRouteImport.update({
  id: '/api/whatsapp/hub',
  path: '/api/whatsapp/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappIngestRoute = ApiWhatsappIngestRouteImport.update({
  id: '/api/whatsapp/ingest',
  path: '/api/whatsapp/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/groups': typeof GroupsRouteWithChildren
  '/groups/$id': typeof GroupsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/whatsapp/hub': typeof ApiWhatsappHubRoute
  '/api/whatsapp/ingest': typeof ApiWhatsappIngestRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/groups': typeof GroupsRouteWithChildren
  '/groups/$id': typeof GroupsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/whatsapp/hub': typeof ApiWhatsappHubRoute
  '/api/whatsapp/ingest': typeof ApiWhatsappIngestRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/groups': typeof GroupsRouteWithChildren
  '/groups/$id': typeof GroupsIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/whatsapp/hub': typeof ApiWhatsappHubRoute
  '/api/whatsapp/ingest': typeof ApiWhatsappIngestRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/groups'
    | '/groups/$id'
    | '/listings/$id'
    | '/api/media/$id'
    | '/api/whatsapp/hub'
    | '/api/whatsapp/ingest'
    | '/api/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desk'
    | '/groups'
    | '/groups/$id'
    | '/listings/$id'
    | '/api/media/$id'
    | '/api/whatsapp/hub'
    | '/api/whatsapp/ingest'
    | '/api/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/groups'
    | '/groups/$id'
    | '/listings/$id'
    | '/api/media/$id'
    | '/api/whatsapp/hub'
    | '/api/whatsapp/ingest'
    | '/api/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  ListingsIdRoute: typeof ListingsIdRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ApiWhatsappHubRoute: typeof ApiWhatsappHubRoute
  ApiWhatsappIngestRoute: typeof ApiWhatsappIngestRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/hub': {
      id: '/api/whatsapp/hub'
      path: '/api/whatsapp/hub'
      fullPath: '/api/whatsapp/hub'
      preLoaderRoute: typeof ApiWhatsappHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/ingest': {
      id: '/api/whatsapp/ingest'
      path: '/api/whatsapp/ingest'
      fullPath: '/api/whatsapp/ingest'
      preLoaderRoute: typeof ApiWhatsappIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GroupsRouteChildren {
  GroupsIdRoute: typeof GroupsIdRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsIdRoute: GroupsIdRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  GroupsRoute: GroupsRouteWithChildren,
  ListingsIdRoute: ListingsIdRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
  ApiWhatsappHubRoute: ApiWhatsappHubRoute,
  ApiWhatsappIngestRoute: ApiWhatsappIngestRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
